### ISSUE TITLE
POST Bulk error unmarshalling payload

### ISSUE THREAD

**Issue by DesistDaydream** [facebookincubator/prometheus-configmanager#27]
### Your Environment

- **Version:** latest
- **Deployment Environment:** local

### Describe the Issue
All interface prometheus struct doesn't work,because the for field is a `string`, but the struct is `model.Duration`.
BUT
POST `/alert` and `/alert/bulk`  are different，`/alert/bulk` Not using `alert.RuleJSONWrapper{}`

https://github.com/facebookincubator/prometheus-configmanager/blob/28865b92d22d57ffcb15d94435a2d71e59471bba/prometheus/handlers/handlers.go#L257
https://github.com/facebookincubator/prometheus-configmanager/blob/28865b92d22d57ffcb15d94435a2d71e59471bba/prometheus/handlers/handlers.go#L277

**To Reproduce**
```
curl -X POST "http://localhost:9100/v1/lichenhao/alert/bulk" -H  "accept: application/json" -H  "Content-Type: application/json" -d '
[{
  "alert": "test1",
  "expr": "string",
  "labels": {
    "additionalProp1": "string"
  },
  "for": "1m",
  "annotations": {
    "additionalProp1": "string"
  }
},
{
  "alert": "test2",
  "expr": "string",
  "labels": {
    "additionalProp1": "string"
  },
  "for": "1m",
  "annotations": {
    "additionalProp1": "string"
  }
}
]'
```
2. See error
```
{"message":"error unmarshalling payload: json: cannot unmarshal string into Go struct field Rule.For of type model.Duration"}
```

**Expected behavior**
`/{tenant_id}/alert/bulk` should be able to handle the string type of the `for` field correctly

**Comment by Scott8440** [comment]
Good catch! I'll make a fix for this soon.
